### PR TITLE
add support for Jewish twilight, AKA havdalah, at 8.5 degrees

### LINKED ISSUE #20: Add support for Jewish dusk
It would be great if the `wait` command of this project could support "Jewish dusk", more commonly known as the time in the evening when the ritual of havdalah is done. (Other names for this time that you'll find if you look around the web are "tzeit hakochavim" or "the appearance of three stars".) The time for this is not universally agreed upon, but the most commonly used time is when the center of the sun is 8.5 degrees below the horizon.

### PR DESCRIPTION
**Pull request by rosenbergj**
Closes #20.

### CODE REVIEW

**Comment by rosenbergj** [comment]
(Never programmed in rust before, but since this is mostly a copy-and-paste job, I decided to give it a shot.)

**Comment by mfreeborn** [comment]
Thanks very much fore the interest and the PR. I see it's just tripping over the tests, I need to refactor them anyway; there's a lot of repetition in setting up the `SolarReport` instance, for example.

I think that support for other dawn/dusk times is a great idea. I only wonder if it would be better to implement it as a new CLI option for the `wait` subcommand.

`heliocron wait --event custom --twilight-angle 8.5`, for example.

The balance is between preventing the explosion of different twilight types (I don't know how many different religions/cultures have significant twilights), not having an unwieldy amount of CLI options, future flexibility of the program and necessity of each feature.

The more I think about it, the more it might be better in the long run to add a `custom` twilight type and require the user to provide an angle as a positive float.

What do you think?

**Comment by rosenbergj** [comment]
I would be equally happy with `custom`! But I fear my (lack of) Rust skills would not be up to a PR for that.

**Comment by mfreeborn** [comment]
closed by #26

**Pull request closed without merging**
